// Generic adult reference values use the current FDA Daily Values. `null`
// means the FDA does not define a label Daily Value for that nutrient.
export const TRACKED_NUTRIENTS = [
  {
    key: "fiber_g",
    en: "Fiber",
    sv: "Fiber",
    unit: "g",
    dailyValue: 28,
    kind: "goal",
    group: "other",
  },
  {
    key: "total_sugars_g",
    en: "Total sugars",
    sv: "Totalt socker",
    unit: "g",
    dailyValue: null,
    kind: "neutral",
    group: "other",
  },
  {
    key: "added_sugars_g",
    en: "Added sugars",
    sv: "Tillsatt socker",
    unit: "g",
    dailyValue: 50,
    kind: "limit",
    group: "other",
  },
  {
    key: "saturated_fat_g",
    en: "Saturated fat",
    sv: "Mättat fett",
    unit: "g",
    dailyValue: 20,
    kind: "limit",
    group: "other",
  },
  {
    key: "trans_fat_g",
    en: "Trans fat",
    sv: "Transfett",
    unit: "g",
    dailyValue: null,
    kind: "limit",
    group: "other",
  },
  {
    key: "monounsaturated_fat_g",
    en: "Monounsaturated fat",
    sv: "Enkelomättat fett",
    unit: "g",
    dailyValue: null,
    kind: "neutral",
    group: "other",
  },
  {
    key: "polyunsaturated_fat_g",
    en: "Polyunsaturated fat",
    sv: "Fleromättat fett",
    unit: "g",
    dailyValue: null,
    kind: "neutral",
    group: "other",
  },
  {
    key: "omega_3_g",
    en: "Omega-3",
    sv: "Omega-3",
    unit: "g",
    dailyValue: null,
    kind: "neutral",
    group: "other",
  },
  {
    key: "omega_6_g",
    en: "Omega-6",
    sv: "Omega-6",
    unit: "g",
    dailyValue: null,
    kind: "neutral",
    group: "other",
  },
  {
    key: "cholesterol_mg",
    en: "Cholesterol",
    sv: "Kolesterol",
    unit: "mg",
    dailyValue: 300,
    kind: "limit",
    group: "other",
  },
  {
    key: "sodium_mg",
    en: "Sodium",
    sv: "Natrium",
    unit: "mg",
    dailyValue: 2300,
    kind: "limit",
    group: "minerals",
  },
  {
    key: "potassium_mg",
    en: "Potassium",
    sv: "Kalium",
    unit: "mg",
    dailyValue: 4700,
    kind: "goal",
    group: "minerals",
  },
  {
    key: "calcium_mg",
    en: "Calcium",
    sv: "Kalcium",
    unit: "mg",
    dailyValue: 1300,
    kind: "goal",
    group: "minerals",
  },
  {
    key: "iron_mg",
    en: "Iron",
    sv: "Järn",
    unit: "mg",
    dailyValue: 18,
    kind: "goal",
    group: "minerals",
  },
  {
    key: "magnesium_mg",
    en: "Magnesium",
    sv: "Magnesium",
    unit: "mg",
    dailyValue: 420,
    kind: "goal",
    group: "minerals",
  },
  {
    key: "zinc_mg",
    en: "Zinc",
    sv: "Zink",
    unit: "mg",
    dailyValue: 11,
    kind: "goal",
    group: "minerals",
  },
  {
    key: "selenium_mcg",
    en: "Selenium",
    sv: "Selen",
    unit: "mcg",
    dailyValue: 55,
    kind: "goal",
    group: "minerals",
  },
  {
    key: "phosphorus_mg",
    en: "Phosphorus",
    sv: "Fosfor",
    unit: "mg",
    dailyValue: 1250,
    kind: "goal",
    group: "minerals",
  },
  {
    key: "copper_mg",
    en: "Copper",
    sv: "Koppar",
    unit: "mg",
    dailyValue: 0.9,
    kind: "goal",
    group: "minerals",
  },
  {
    key: "manganese_mg",
    en: "Manganese",
    sv: "Mangan",
    unit: "mg",
    dailyValue: 2.3,
    kind: "goal",
    group: "minerals",
  },
  {
    key: "iodine_mcg",
    en: "Iodine",
    sv: "Jod",
    unit: "mcg",
    dailyValue: 150,
    kind: "goal",
    group: "minerals",
  },
  {
    key: "chloride_mg",
    en: "Chloride",
    sv: "Klorid",
    unit: "mg",
    dailyValue: 2300,
    kind: "goal",
    group: "minerals",
  },
  {
    key: "chromium_mcg",
    en: "Chromium",
    sv: "Krom",
    unit: "mcg",
    dailyValue: 35,
    kind: "goal",
    group: "minerals",
  },
  {
    key: "molybdenum_mcg",
    en: "Molybdenum",
    sv: "Molybden",
    unit: "mcg",
    dailyValue: 45,
    kind: "goal",
    group: "minerals",
  },
  {
    key: "vitamin_a_mcg",
    en: "Vitamin A",
    sv: "Vitamin A",
    unit: "mcg",
    dailyValue: 900,
    kind: "goal",
    group: "vitamins",
  },
  {
    key: "vitamin_c_mg",
    en: "Vitamin C",
    sv: "Vitamin C",
    unit: "mg",
    dailyValue: 90,
    kind: "goal",
    group: "vitamins",
  },
  {
    key: "vitamin_d_mcg",
    en: "Vitamin D",
    sv: "Vitamin D",
    unit: "mcg",
    dailyValue: 20,
    kind: "goal",
    group: "vitamins",
  },
  {
    key: "vitamin_e_mg",
    en: "Vitamin E",
    sv: "Vitamin E",
    unit: "mg",
    dailyValue: 15,
    kind: "goal",
    group: "vitamins",
  },
  {
    key: "vitamin_k_mcg",
    en: "Vitamin K",
    sv: "Vitamin K",
    unit: "mcg",
    dailyValue: 120,
    kind: "goal",
    group: "vitamins",
  },
  {
    key: "thiamin_b1_mg",
    en: "Vitamin B1",
    sv: "Vitamin B1",
    unit: "mg",
    dailyValue: 1.2,
    kind: "goal",
    group: "vitamins",
  },
  {
    key: "riboflavin_b2_mg",
    en: "Vitamin B2",
    sv: "Vitamin B2",
    unit: "mg",
    dailyValue: 1.3,
    kind: "goal",
    group: "vitamins",
  },
  {
    key: "niacin_b3_mg",
    en: "Vitamin B3",
    sv: "Vitamin B3",
    unit: "mg",
    dailyValue: 16,
    kind: "goal",
    group: "vitamins",
  },
  {
    key: "pantothenic_b5_mg",
    en: "Vitamin B5",
    sv: "Vitamin B5",
    unit: "mg",
    dailyValue: 5,
    kind: "goal",
    group: "vitamins",
  },
  {
    key: "vitamin_b6_mg",
    en: "Vitamin B6",
    sv: "Vitamin B6",
    unit: "mg",
    dailyValue: 1.7,
    kind: "goal",
    group: "vitamins",
  },
  {
    key: "biotin_b7_mcg",
    en: "Vitamin B7",
    sv: "Vitamin B7",
    unit: "mcg",
    dailyValue: 30,
    kind: "goal",
    group: "vitamins",
  },
  {
    key: "folate_b9_mcg",
    en: "Vitamin B9",
    sv: "Vitamin B9",
    unit: "mcg",
    dailyValue: 400,
    kind: "goal",
    group: "vitamins",
  },
  {
    key: "vitamin_b12_mcg",
    en: "Vitamin B12",
    sv: "Vitamin B12",
    unit: "mcg",
    dailyValue: 2.4,
    kind: "goal",
    group: "vitamins",
  },
  {
    key: "choline_mg",
    en: "Choline",
    sv: "Kolin",
    unit: "mg",
    dailyValue: 550,
    kind: "goal",
    group: "vitamins",
  },
] as const;

export type NutrientKey = (typeof TRACKED_NUTRIENTS)[number]["key"];
export type FoodNutrientEstimates = Partial<Record<NutrientKey, number | null>>;
export type NutrientGroup = (typeof TRACKED_NUTRIENTS)[number]["group"];

export const NUTRIENT_KEYS = TRACKED_NUTRIENTS.map((nutrient) => nutrient.key);

export function emptyNutrientTotals(): Record<NutrientKey, number> {
  return Object.fromEntries(NUTRIENT_KEYS.map((key) => [key, 0])) as Record<NutrientKey, number>;
}
