ALTER TABLE "program_days" DROP CONSTRAINT "program_days_date_check";--> statement-breakpoint
ALTER TABLE "programs" DROP CONSTRAINT "programs_dates_check";--> statement-breakpoint
ALTER TABLE "workout_sessions" DROP CONSTRAINT "workout_sessions_date_check";--> statement-breakpoint
ALTER TABLE "meal_logs" ALTER COLUMN "logged_date" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "measurements" ALTER COLUMN "recorded_date" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "weight_logs" ALTER COLUMN "logged_date" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "session_sets" ADD COLUMN "revision" integer DEFAULT 0 NOT NULL;--> statement-breakpoint

-- Make the legacy backfill policy explicit. These rows were assigned their UTC
-- calendar date by 0012 because the old schema did not retain a user timezone.
UPDATE "meal_logs" SET "timezone" = 'UTC' WHERE "timezone" IS NULL;--> statement-breakpoint
UPDATE "weight_logs" SET "timezone" = 'UTC' WHERE "timezone" IS NULL;--> statement-breakpoint

-- Repair timestamp-side lifecycle invariants without inventing performed
-- values. A completed exercise with incomplete sets is reopened; otherwise its
-- completion time is recovered from its last exact set timestamp.
UPDATE "session_exercises" exercise
SET
	"completed" = false,
	"completed_at" = NULL
WHERE
	exercise."completed"
	AND (
		NOT EXISTS (
			SELECT 1 FROM "session_sets" session_set
			WHERE session_set."session_exercise_id" = exercise."id"
		)
		OR EXISTS (
			SELECT 1 FROM "session_sets" session_set
			WHERE
				session_set."session_exercise_id" = exercise."id"
				AND (
					NOT session_set."completed"
					OR session_set."reps" IS NULL
					OR session_set."completed_at" IS NULL
				)
		)
	);--> statement-breakpoint
UPDATE "session_exercises" exercise
SET "completed_at" = completed_sets."completed_at"
FROM (
	SELECT
		"session_exercise_id",
		max("completed_at") AS "completed_at"
	FROM "session_sets"
	WHERE "completed"
	GROUP BY "session_exercise_id"
) completed_sets
WHERE
	exercise."id" = completed_sets."session_exercise_id"
	AND exercise."completed"
	AND exercise."completed_at" IS NULL;--> statement-breakpoint
UPDATE "workout_sessions" session
SET "completed_at" = performed."completed_at"
FROM (
	SELECT
		exercise."session_id",
		max(session_set."completed_at") AS "completed_at"
	FROM "session_exercises" exercise
	JOIN "session_sets" session_set
		ON session_set."session_exercise_id" = exercise."id"
	WHERE session_set."completed" AND session_set."completed_at" IS NOT NULL
	GROUP BY exercise."session_id"
) performed
WHERE
	session."id" = performed."session_id"
	AND session."status" = 'completed'
	AND session."completed_at" IS NULL;--> statement-breakpoint
UPDATE "workout_sessions"
SET "completed_at" = "created_at"
WHERE "status" = 'completed' AND "completed_at" IS NULL;--> statement-breakpoint
UPDATE "programs"
SET "completed_at" = "created_at"
WHERE "status" = 'completed' AND "completed_at" IS NULL;--> statement-breakpoint
UPDATE "programs"
SET "completed_at" = NULL
WHERE "status" = 'active' AND "completed_at" IS NOT NULL;--> statement-breakpoint
UPDATE "program_days" day
SET "session_id" = completed_session."id"
FROM "workout_sessions" completed_session
WHERE
	day."status" = 'completed'
	AND day."session_id" IS NULL
	AND completed_session."program_day_id" = day."id"
	AND completed_session."status" = 'completed';--> statement-breakpoint
UPDATE "program_days" day
SET
	"status" = CASE WHEN program."status" = 'active' THEN 'planned' ELSE 'skipped' END,
	"resolution_note" = concat_ws(
		' ',
		nullif(day."resolution_note", ''),
		CASE
			WHEN program."status" = 'active'
				THEN 'Reopened during integrity repair because no exact completed session could be linked.'
			ELSE 'Not counted as completed during integrity repair because no exact completed session could be linked.'
		END
	)
FROM "programs" program
WHERE
	day."program_id" = program."id"
	AND day."status" = 'completed'
	AND day."session_id" IS NULL;--> statement-breakpoint

-- Existing source keys were generated by older code without a database length
-- bound. Preserve their identity deterministically rather than truncating two
-- distinct keys into the same value.
UPDATE "meal_logs"
SET "source_key" = 'legacy:' || md5("source_key")
WHERE "source_key" IS NOT NULL AND length("source_key") NOT BETWEEN 1 AND 200;--> statement-breakpoint
UPDATE "measurements"
SET "source_key" = 'legacy:' || md5("source_key")
WHERE "source_key" IS NOT NULL AND length("source_key") NOT BETWEEN 1 AND 200;--> statement-breakpoint
UPDATE "programs"
SET "source_key" = 'legacy:' || md5("source_key")
WHERE "source_key" IS NOT NULL AND length("source_key") NOT BETWEEN 1 AND 200;--> statement-breakpoint
UPDATE "weight_logs"
SET "source_key" = 'legacy:' || md5("source_key")
WHERE "source_key" IS NOT NULL AND length("source_key") NOT BETWEEN 1 AND 200;--> statement-breakpoint
UPDATE "workout_sessions"
SET "source_key" = 'legacy:' || md5("source_key")
WHERE "source_key" IS NOT NULL AND length("source_key") NOT BETWEEN 1 AND 200;--> statement-breakpoint

-- A metric key has one durable meaning and unit for an account. The advisory
-- lock closes the first-insert race across replicas; the trigger protects the
-- invariant even if a future writer bypasses the TypeScript service.
DO $measurement_preflight$
BEGIN
	IF EXISTS (
		SELECT 1
		FROM "measurements"
		GROUP BY "user_id", "metric_key"
		HAVING count(DISTINCT "label") > 1 OR count(DISTINCT "unit") > 1
	) THEN
		RAISE EXCEPTION '0016 preflight: a measurement key has conflicting labels or units';
	END IF;
END
$measurement_preflight$;--> statement-breakpoint
CREATE OR REPLACE FUNCTION "enforce_measurement_definition"()
RETURNS trigger
LANGUAGE plpgsql
AS $measurement_definition$
BEGIN
	PERFORM pg_advisory_xact_lock(
		hashtextextended(
			'measurement-definition:' || NEW."user_id"::text || ':' || NEW."metric_key",
			0
		)
	);
	IF EXISTS (
		SELECT 1
		FROM "measurements" existing
		WHERE
			existing."user_id" = NEW."user_id"
			AND existing."metric_key" = NEW."metric_key"
			AND existing."id" <> NEW."id"
			AND (
				existing."label" IS DISTINCT FROM NEW."label"
				OR existing."unit" IS DISTINCT FROM NEW."unit"
			)
	) THEN
		RAISE EXCEPTION USING
			ERRCODE = '23514',
			CONSTRAINT = 'measurements_definition_consistency',
			MESSAGE = 'measurement key label/unit conflicts with its existing definition';
	END IF;
	RETURN NEW;
END
$measurement_definition$;--> statement-breakpoint
CREATE TRIGGER "measurements_definition_consistency_trigger"
BEFORE INSERT OR UPDATE OF "user_id", "metric_key", "label", "unit"
ON "measurements"
FOR EACH ROW
EXECUTE FUNCTION "enforce_measurement_definition"();--> statement-breakpoint

DO $calendar_preflight$
BEGIN
	IF EXISTS (
		SELECT 1
		FROM "program_days"
		WHERE CASE
			WHEN "date" ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}$'
				THEN to_char(to_date("date", 'YYYY-MM-DD'), 'YYYY-MM-DD') <> "date"
			ELSE true
		END
	) THEN
		RAISE EXCEPTION '0016 preflight: invalid program calendar date';
	END IF;
	IF EXISTS (
		SELECT 1
		FROM "programs"
		WHERE
			CASE
				WHEN
					"start_date" ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}$'
					AND "end_date" ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}$'
				THEN
					to_char(to_date("start_date", 'YYYY-MM-DD'), 'YYYY-MM-DD') <> "start_date"
					OR to_char(to_date("end_date", 'YYYY-MM-DD'), 'YYYY-MM-DD') <> "end_date"
					OR "end_date" < "start_date"
				ELSE true
			END
	) THEN
		RAISE EXCEPTION '0016 preflight: invalid program start/end date';
	END IF;
	IF EXISTS (
		SELECT 1
		FROM "workout_sessions"
		WHERE CASE
			WHEN "session_date" ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}$'
				THEN to_char(to_date("session_date", 'YYYY-MM-DD'), 'YYYY-MM-DD') <> "session_date"
			ELSE true
		END
	) THEN
		RAISE EXCEPTION '0016 preflight: invalid workout session date';
	END IF;
END
$calendar_preflight$;--> statement-breakpoint
ALTER TABLE "meal_logs" ADD CONSTRAINT "meal_logs_source_length_check" CHECK ("meal_logs"."source_key" IS NULL OR length("meal_logs"."source_key") BETWEEN 1 AND 200);--> statement-breakpoint
ALTER TABLE "measurements" ADD CONSTRAINT "measurements_source_length_check" CHECK ("measurements"."source_key" IS NULL OR length("measurements"."source_key") BETWEEN 1 AND 200);--> statement-breakpoint
ALTER TABLE "program_days" ADD CONSTRAINT "program_days_completed_session_check" CHECK ("program_days"."status" <> 'completed' OR "program_days"."session_id" IS NOT NULL);--> statement-breakpoint
ALTER TABLE "program_days" ADD CONSTRAINT "program_days_date_check" CHECK ("program_days"."date" ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}$' AND ("program_days"."date"::date)::text = "program_days"."date");--> statement-breakpoint
ALTER TABLE "programs" ADD CONSTRAINT "programs_source_length_check" CHECK ("programs"."source_key" IS NULL OR length("programs"."source_key") BETWEEN 1 AND 200);--> statement-breakpoint
ALTER TABLE "programs" ADD CONSTRAINT "programs_completion_time_check" CHECK (("programs"."status" = 'completed' AND "programs"."completed_at" IS NOT NULL) OR ("programs"."status" = 'active' AND "programs"."completed_at" IS NULL) OR "programs"."status" = 'archived');--> statement-breakpoint
ALTER TABLE "programs" ADD CONSTRAINT "programs_dates_check" CHECK ("programs"."start_date" ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}$' AND ("programs"."start_date"::date)::text = "programs"."start_date" AND "programs"."end_date" ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}$' AND ("programs"."end_date"::date)::text = "programs"."end_date" AND "programs"."end_date" >= "programs"."start_date");--> statement-breakpoint
ALTER TABLE "session_exercises" ADD CONSTRAINT "session_exercises_completion_time_check" CHECK (NOT "session_exercises"."completed" OR "session_exercises"."completed_at" IS NOT NULL);--> statement-breakpoint
ALTER TABLE "session_sets" ADD CONSTRAINT "session_sets_revision_check" CHECK ("session_sets"."revision" >= 0);--> statement-breakpoint
ALTER TABLE "weight_logs" ADD CONSTRAINT "weight_logs_source_length_check" CHECK ("weight_logs"."source_key" IS NULL OR length("weight_logs"."source_key") BETWEEN 1 AND 200);--> statement-breakpoint
ALTER TABLE "workout_sessions" ADD CONSTRAINT "workout_sessions_source_length_check" CHECK ("workout_sessions"."source_key" IS NULL OR length("workout_sessions"."source_key") BETWEEN 1 AND 200);--> statement-breakpoint
ALTER TABLE "workout_sessions" ADD CONSTRAINT "workout_sessions_completion_time_check" CHECK ("workout_sessions"."status" <> 'completed' OR "workout_sessions"."completed_at" IS NOT NULL);--> statement-breakpoint
ALTER TABLE "workout_sessions" ADD CONSTRAINT "workout_sessions_date_check" CHECK ("workout_sessions"."session_date" ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}$' AND ("workout_sessions"."session_date"::date)::text = "workout_sessions"."session_date");
